export const CREATE_NEW_MESSAGE="CREATE_NEW_MESSAGE";
export const GET_ALL_MESSAGE="GET_ALL_MESSAGE";
export const ADD_MESSAGE="Add ALL MESSAGE";
// export const NEW_MESSAGE_RECEIVED="NEW_MESSAGE_RECEIVED";
